### PR TITLE
feat: add vpc_config

### LINKED ISSUE #3: Allow configuration of a vpc for lambdas
## what

Allow configuration of a vpc for lambdas

## why

This is helpful because

1. deterministic IP addresses of lambdas behind a NAT so we can allowlist specific IPs to interface with API tokens such as cloudflare api tokens
    - This way if any tokens leak, they cannot be used from any IP other than the one that has been allowed
1. vpc usage is recommended for security best practices so we can get rid of the checkov warning

## implementation

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function

The `vpc_config` can be used to provision the lambda in a vpc along with a security group

```hcl
  vpc_config {
    # Every subnet should be able to reach an EFS mount target in the same Availability Zone. Cross-AZ mounts are not permitted.
    subnet_ids         = [aws_subnet.subnet_for_lambda.id]
    security_group_ids = [aws_security_group.sg_for_lambda.id]
  }
```

It can be optional. Next major release should require it for security best practices.

## references
- https://github.com/domain-protect/terraform-aws-domain-protect/blob/cb6dcd3b671c095ade2fc74fe476998a5d46cbf8/terraform-modules/lambda-accounts/main.tf#L28-L31
- https://github.com/domain-protect/domain-protect/blob/2a299b93c000663602e5dcba882399d0ae2cbc20/terraform-modules/lambda-accounts/main.tf#L28-L31
- PR https://github.com/domain-protect/domain-protect/pull/89

### PR DESCRIPTION
**Pull request by nitrocode**
## what
- Allow adding vpcs to lambdas

## why
- Reduce securityhub complaints

## references
- Closes https://github.com/domain-protect/terraform-aws-domain-protect/issues/3
- Borrowed from
    - https://github.com/cloudposse/terraform-aws-lambda-function/blob/670c7fab0ed10e9deb8c5df1c808cae00dae684a/variables.tf#L209-L219
    - https://github.com/cloudposse/terraform-aws-lambda-function/blob/670c7fab0ed10e9deb8c5df1c808cae00dae684a/main.tf#L76-L82

### CODE REVIEW

**Review by paulschwarzenberger — COMMENTED** [review]
For this option to work, there would need to be network connectivity to the Internet via a NAT Gateway or similar, with security group rules allowing the various API calls (AWS APIs, CloudFlare, Bug Bounty, DNS to Google DNS servers).

Should we include a security group for the Lambda VPC interface to allow this access? Or mention this requirement in the variable description or documentation?

**Comment by nitrocode** [comment]
I agree that we could probably provide a security group. 

For now, we can allow the consumer to provider both a VPC and security group.

We can add a new option to say if the security group is not provided (so it can be `optional` in the variable definition), the module will provide a security group on behalf of the consumer and provide it to each module.

Or we can wait until I test out the security group rules and we provide both the vpc_config and module security group in the same PR.

What do you think?

**Comment by paulschwarzenberger** [comment]
I generally favour smaller PRs, so I'm inclined to keep this one with just the VPC part, and then follow that up with a 2nd PR to provide a security group, and as you suggest also provide the option to reference an existing security group outside of Terraform.
The security group ID should be an output of the Terraform module in case the user wants to add extra rules to it.

**Review by paulschwarzenberger — APPROVED** [review]
LGTM

**Pull request merged**
